4 implement a circuit stage
nunezco2/quAPL pull request #24
Opened 2023-04-28 01:47 UTC by marcosfrenkel

Not ready for merging yet, but in a stage ready to be shown. Variable names are not final, still finding bugs and extremely finicky about how it likes its arguments being passed.

basic example:

      reg4 ← reg 4
      reg4[1;2] ← ⊂q1
      reg4[2;2] ← ⊂(H+.×q0)
      gates ← (H 2) (CNOT (0 3)) 
      (1) gates apply_stage (thread_reg reg4)

You are measuring qubit 1 and applying a CNOT gate with qubit 0 as control and 3 as target and an H gate to qubit 2

2023-05-09 19:55 UTC, nunezco2 requested changes

2023-05-09 19:55 UTC, nunezco2 commented on src/qc_ncsa.aplf
> +        ⍝ Returns the measured state of the qubit and the new normalized vector state vector state of all the qubits.
Remove repetition

2023-05-09 22:25 UTC, marcosfrenkel commented on src/qc_ncsa.aplf
> +        ⍝ Returns the measured state of the qubit and the new normalized vector state vector state of all the qubits.
This will get fixed with PR #27

2023-05-09 22:27 UTC, marcosfrenkel commented
I found a bug when trying to apply a CNOT gate from example from qubit 4 to qubit 0, for some reason nothing seems to be happening and I could not figure out why this was the case. Maybe we could discuss it in person

2023-05-10 15:07 UTC, nunezco2 approved these changes
Marcos, this is great! The `stage` function is way, way simpler.

2023-05-10 15:07 UTC, merged