Adding test_unitary function
nunezco2/quAPL pull request #45
Opened 2023-07-03 19:05 UTC by BachHV

Created a test_unitary function by checking the multiplication between the gate and its transpose conjugate equals to the generated unitary matrix.

2023-07-03 19:07 UTC, nunezco2 requested changes

2023-07-03 19:07 UTC, nunezco2 commented on APLSource/quapl.aplf
> +        sum←⍵+.×(⍉+⍵)
Add two spaces, one before the arrow operator, and one after

2023-07-03 19:10 UTC, nunezco2 approved these changes

2023-07-03 19:13 UTC, marcosfrenkel commented
How are you running the test? Do you just pass a gate as the right argument of the function and see if it returns 1 or 0?

2024-02-27 21:41 UTC, closed without merging

2024-02-27 21:41 UTC, nunezco2 commented
Superseded by new testing framework.