70 what tests do we need
nunezco2/quAPL pull request #72
Opened 2024-02-14 22:50 UTC by marcosfrenkel

Added tests for almost all of quAPL.

Tests for the show module are missing, since I don't believe this module is ready for them. This is because they lack any sort of tools for multiple qubit vector states. There are some functions for registers, but if you are working with register you already have the qubits separated which I am not sure if that is what the show module should be.

2024-02-14 23:42 UTC, nunezco2 requested changes

2024-02-14 23:42 UTC, nunezco2 commented on Tests/test_thread_003.aplf
> +    a ← 2 1 ⍴ (1÷(2*0.5)) (1÷(2*0.5))
Use an additional variable to avoid repeating this regular pattern.

2024-02-14 23:42 UTC, nunezco2 commented on Tests/test_thread_gate_001.aplf
> +    correct_result ← 4 4⍴(0 (0.5*0.5) 0 (0.5*0.5) (0.5*0.5) 0 (0.5*0.5) 0 0 (0.5*0.5) 0 (¯1×0.5*0.5) (0.5*0.5) 0 (¯1×0.5*0.5) 0)
Same here

2024-02-14 23:42 UTC, nunezco2 commented on Tests/test_unkpr_002.aplf
> +    a ← 2 1 ⍴ (1÷(2*0.5)) (1÷(2*0.5))
Same here

2024-02-14 23:42 UTC, nunezco2 commented on Tests/test_unthread_vs_001.aplf
> +    c ← 2 1 ⍴ 1 0
Identical, use only one

2024-02-14 23:42 UTC, nunezco2 commented on Tests/test_unthread_vs_002.aplf
> +    a ← 2 1 ⍴ (1÷(2*0.5)) (1÷(2*0.5))
Same here, single value then use variable

2024-02-14 23:42 UTC, nunezco2 commented on Tests/test_unthread_vs_003.aplf
> +    a ← 2 1 ⍴ (1÷(2*0.5)) (1÷(2*0.5))
Use single variable, use one larger assignment only later

2024-02-14 23:42 UTC, nunezco2 commented on failed_tests/test_qx_value_002.aplf
> +     correct_value ← 2 1 ⍴ ((1÷(82*0.5))(9÷(82*0.5)))
Same here

2024-02-20 22:49 UTC, marcosfrenkel commented
@nunezco2  I cleaned up all of the inconsistent whitespace between all the files. I have also removed any repeated pattern. Let me know if you like the way I fixed it (wasn't entirely sure if that is what you meant)

2024-02-21 19:13 UTC, nunezco2 approved these changes

2024-02-21 19:13 UTC, merged